### ISSUE TITLE
install problems

### ISSUE THREAD

**Issue by alemol** [mgraffg/EvoDAG#52]
(venv) amolina@keken:~/repo/EvoMSA$ pip install EvoDAG
Collecting EvoDAG
  Using cached https://files.pythonhosted.org/packages/6c/b3/65112b3ae7683bbe56bf15cc0c425c98d7c49ba6476824f67d0fd94b9536/EvoDAG-0.16.0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: /home/amolina/repo/EvoMSA/venv/lib/python3.6/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-nqz9ogww/EvoDAG/EvoDAG/cython_utils.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    warning: EvoDAG/cython_utils.pyx:72:22: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: EvoDAG/cython_utils.pyx:74:16: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: EvoDAG/cython_utils.pyx:75:16: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: EvoDAG/cython_utils.pyx:75:33: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: EvoDAG/cython_utils.pyx:75:50: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: EvoDAG/cython_utils.pyx:124:16: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: EvoDAG/cython_utils.pyx:124:61: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: EvoDAG/cython_utils.pyx:124:77: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: EvoDAG/cython_utils.pyx:151:22: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: EvoDAG/cython_utils.pyx:153:16: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: EvoDAG/cython_utils.pyx:154:16: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: EvoDAG/cython_utils.pyx:154:33: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: EvoDAG/cython_utils.pyx:188:16: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: EvoDAG/cython_utils.pyx:188:58: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: EvoDAG/cython_utils.pyx:590:22: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: EvoDAG/cython_utils.pyx:590:26: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: EvoDAG/cython_utils.pyx:591:16: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: EvoDAG/cython_utils.pyx:591:26: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    /home/amolina/repo/EvoMSA/venv/lib/python3.6/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-nqz9ogww/EvoDAG/EvoDAG/linalg_solve.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    warning: EvoDAG/linalg_solve.pyx:66:16: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: EvoDAG/linalg_solve.pyx:66:30: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: EvoDAG/linalg_solve.pyx:111:21: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    /home/amolina/repo/EvoMSA/venv/lib/python3.6/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-nqz9ogww/EvoDAG/EvoDAG/function_selection.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            return False
    
        cpdef int tournament(self) except -1:
            cdef int best, comp
            cdef double best_fit, comp_fit
            cdef unsigned int *nargs = self.nargs.data.as_uints
                                                     ^
    ------------------------------------------------------------
    
    EvoDAG/function_selection.pyx:85:50: Cannot convert Python object to 'unsigned int *'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-nqz9ogww/EvoDAG/setup.py", line 63, in <module>
        'boundscheck': False}),
      File "/home/amolina/repo/EvoMSA/venv/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1097, in cythonize
        cythonize_one(*args)
      File "/home/amolina/repo/EvoMSA/venv/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1220, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: EvoDAG/function_selection.pyx
    Compiling EvoDAG/linalg_solve.pyx because it depends on /home/amolina/repo/EvoMSA/venv/lib/python3.6/site-packages/SparseArray/sparse_array.pxd.
    Compiling EvoDAG/function_selection.pyx because it depends on /home/amolina/repo/EvoMSA/venv/lib/python3.6/site-packages/Cython/Includes/cpython/weakref.pxd.
    Compiling EvoDAG/cython_utils.pyx because it depends on /home/amolina/repo/EvoMSA/venv/lib/python3.6/site-packages/SparseArray/sparse_array.pxd.
    [1/3] Cythonizing EvoDAG/cython_utils.pyx
    [2/3] Cythonizing EvoDAG/linalg_solve.pyx
    [3/3] Cythonizing EvoDAG/function_selection.pyx
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-nqz9ogww/EvoDAG/
(venv) amolina@keken:~/repo/EvoMSA$ pip3 freeze
b4msa==2.1
Cython==0.29.7
microtc==2.1.1
numpy==1.16.3
SparseArray==0.8.15

**Comment by mgraffg** [comment]
Estimado Alejandro:

No logró replicar el error que me envías. 

Normalmente lo pruebo utilizando la distribución de conda y en python 3. 

Y me acabo de dar cuenta que funciona en 

https://colab.research.google.com

!pip install evodag

Ahora veo que ya tienes todas las dependencias instaladas entonces igual un clone al repositorio
y 

$ python setup.py install 

podría funciona. 

Me acabo de dar cuenta por tu path, que igual tu interés es hacer funcionar EvoMSA, creo que mi mejor
recomendación sería utilizar conda, aunque también lo puedes probar en colab, hace rato
verifiqué que funcionara, porque no lo hacía en versiones anteriores. 

Las instrucciones con las que pruebo son:

  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then curl -L -o miniconda.sh http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh; fi
  - chmod 755 miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n ingeotec python=3.7
  - source activate ingeotec 
  - conda config --append channels ingeotec  
  - conda install --yes numpy scipy scikit-learn nltk nose b4msa evodag conceptmodelling cython evomsa
  - python -c "import nltk; nltk.download('stopwords')"

Las tome del githubb .travis.yml entonces "$TRAVIS_OS_NAME" indica el sistema operativo y solamente se usa 
para bajar miniconda

Espero que esta información ayude aunque sea un poco, quedo al pendiente de cualquier comentario. 

Saludos. 

Mario

**Comment by alemol** [comment]
Gracias,
parece que ya funciona. Estaba intentando hacerlo funcionar en un ambiente virtual pero ahora que probe en global ya funcionó clonando y haciendo un 

`$ python3 setup.py install`
